### ISSUE TITLE
-- retrying in 10 seconds due to status = 429

### ISSUE THREAD

**Issue by firmshare** [olamigokayphils/blockio-multisig-sweep#6]
After 20 addresses (BTC) got error: 
-- retrying in 10 seconds due to status = 429, and script doesn't go futher..
Is it possible to add timeout between requests in constants.js, please?
According to blockchain.info [docs](https://www.blockchain.com/explorer/api/q) they have rate limit 1 request every 10 seconds

**Comment by firmshare** [comment]
Temporary solved it, but adding timeout 10s in "createBalanceMap" function (inside "for" cycle). But im not familiar with js to make beauty code.

**Comment by olamigokayphils** [comment]
@firmshare Can you confirm this isn't a local network issue? I've recently ran it successfully with 3k+ BTC addresses
